markdown: kramdown
exclude:
  - LICENSE
  - Makefile
  - README
markdown_ext: "md"

layouts_dir: ./_noita
baseurl: /85309
piazza: https://piazza.com/class/k59zqdq4g542os
openintro: https://www.openintro.org/stat/textbook.php?stat_book=isrs
teams:

plugins:
  - jemoji

noita:
  name: 85-309 - Statistical Methods and Concepts for Social and Behavioral Sciences
  description: 85-309 - Statistical Methods and Concepts
  author:
    name: Dan Yurovsky
    url: http://callab.github.io
    absolute: true
  lang: en
  topbar:
    toggle: Menu
    right:
      - name: Schedule
        url: /
      - name: Info
        url: /info/
      - name: Syllabus
        url: /syllabus/
      - name: Learning Objectives
        url: /los/
      - name: RStudio
        url: https://rstudio.cloud/spaces/41255/projects
        absolute: true
      - name: Piazza
        url: https://piazza.com/class/k59zqdq4g542os
        absolute: true
